import { useNavigate, useParams, useLocation } from "react-router-dom";
import { useEffect, useState, useRef } from "react";
import { documentApi, commentApi } from "../../services/libraryApi";
import { getDefaultAiUserId } from "../../services/aiChatService";

function documentFileUrl(documentId, action) {
  if (!documentId) return "";
  const apiBase =
    import.meta.env.VITE_API_BASE_URL || "http://localhost:8080/api";
  return `${apiBase.replace(/\/$/, "")}/documents/${documentId}/${action}`;
}

async function fetchDocumentFile(documentId, action) {
  const token = localStorage.getItem("token");
  const response = await fetch(documentFileUrl(documentId, action), {
    headers: token ? { Authorization: `Bearer ${token}` } : {},
  });
  if (!response.ok) {
    const body = await response.json().catch(() => ({}));
    throw new Error(body.message || `Could not ${action} this document.`);
  }
  return response.blob();
}

function hasPreviewSource(doc) {
  return Boolean(doc?.documentId);
}

function cleanSummaryText(text) {
  return String(text || "")
    .replace(/^#{1,6}\s+/gm, "")
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/\*([^*\n]+)\*/g, "$1")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function summaryTakeaways(summary, result) {
  const lines = cleanSummaryText(summary)
    .split(/\r?\n/)
    .map((line) => line.replace(/^[-*\d.)\s]+/, "").trim())
    .filter(Boolean);

  if (lines.length > 0) return lines.slice(0, 3);
  if (result?.chunkCount) return [`Summarized from ${result.chunkCount} chunk(s)`];
  return ["Summary generated by Python AI service"];
}

function getCurrentUser() {
  try {
    const user = JSON.parse(localStorage.getItem("user") || "{}");
    return {
      userId: user.userId ?? user.id ?? null,
      fullName: user.fullName ?? user.name ?? "You",
    };
  } catch {
    return { userId: null, fullName: "You" };
  }
}

function formatCommentTime(value) {
  if (!value) return "";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "";
  return date.toLocaleString([], {
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function initialsFromName(name) {
  return String(name || "User")
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 2)
    .map((part) => part[0]?.toUpperCase())
    .join("") || "U";
}

function normalizeComment(comment) {
  return {
    ...comment,
    id: comment.commentId ?? comment.id,
    name: comment.fullName || comment.name || "Student",
    text: comment.content || comment.text || "",
    time: comment.time || formatCommentTime(comment.createdAt),
    initials: comment.initials || initialsFromName(comment.fullName || comment.name),
    avatarBg: comment.avatarBg || "bg-indigo-50",
    avatarText: comment.avatarText || "text-indigo-600",
  };
}

function normalizeSummaryStatus(doc) {
  return String(doc?.summaryStatus || doc?.summary_status || "").toUpperCase();
}

function isSummaryInProgress(status) {
  return status === "PENDING" || status === "PROCESSING";
}

export default function StudentDocumentViewPage({ _sharedDoc, _shareId } = {}) {
  const navigate = useNavigate();
  const { documentId } = useParams();
  const location = useLocation();
  const initialSummaryResult = location.state?.aiSummaryResult ?? null;
  const initialSummaryError = location.state?.aiSummaryError ?? "";
  const [message, setMessage] = useState("");
  const [comments, setComments] = useState([]);
  const [commentSending, setCommentSending] = useState(false);
  const commentsEndRef = useRef(null);

  const [doc, setDoc] = useState(_sharedDoc ?? location.state?.doc ?? null);
  const [docLoading, setDocLoading] = useState(
    !_sharedDoc && !location.state?.doc,
  );
  const [previewUrl, setPreviewUrl] = useState("");
  const [fileError, setFileError] = useState("");
  const publicAccess = Boolean(_sharedDoc);

  useEffect(() => {
    if (_sharedDoc || location.state?.doc) return; 

    let cancelled = false;
    setDocLoading(true);
    documentApi
      .getById(documentId)
      .then((d) => {
        if (!cancelled) setDoc(d);
      })
      .catch(() => {
        if (!cancelled) setDoc(null);
      })
      .finally(() => {
        if (!cancelled) setDocLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, [documentId]);

  useEffect(() => {
    if (!doc?.documentId) return undefined;
    let objectUrl = "";
    let cancelled = false;
    setPreviewUrl("");
    setFileError("");

    fetchDocumentFile(doc.documentId, "preview")
      .then((blob) => {
        if (cancelled) return;
        objectUrl = URL.createObjectURL(blob);
        setPreviewUrl(objectUrl);
      })
      .catch((error) => {
        if (!cancelled) setFileError(error.message || "Could not load preview.");
      });

    return () => {
      cancelled = true;
      if (objectUrl) URL.revokeObjectURL(objectUrl);
    };
  }, [doc?.documentId]);

  const handleDownload = async () => {
    if (!doc?.documentId) return;
    try {
      setFileError("");
      const blob = await fetchDocumentFile(doc.documentId, "download");
      const objectUrl = URL.createObjectURL(blob);
      const link = window.document.createElement("a");
      link.href = objectUrl;
      link.download = doc.documentName || doc.title || `document-${doc.documentId}`;
      window.document.body.appendChild(link);
      link.click();
      link.remove();
      URL.revokeObjectURL(objectUrl);
    } catch (error) {
      setFileError(error.message || "Could not download this document.");
    }
  };

  const [aiSummary, setAiSummary] = useState(() => {
    if (initialSummaryResult?.summary) {
      const summary = cleanSummaryText(initialSummaryResult.summary);
      return {
        status: "ready",
        takeaways: summaryTakeaways(summary, initialSummaryResult),
        detail: summary,
      };
    }
    if (initialSummaryError) {
      return {
        status: "error",
        takeaways: [],
        detail: initialSummaryError,
      };
    }
    const summaryStatus = normalizeSummaryStatus(doc);
    if (isSummaryInProgress(summaryStatus)) {
      return {
        status: "loading",
        takeaways: [],
        detail: "AI summary is being generated in the background.",
      };
    }
    if (summaryStatus === "FAILED" || summaryStatus === "UNSUPPORTED") {
      return {
        status: "error",
        takeaways: [],
        detail:
          doc?.summaryError ||
          "AI summary could not be generated for this document.",
      };
    }
    return {
      status: "idle", // idle | loading | ready | error
      takeaways: [
        "Document uploaded to AI StudyHub",
        "AI analysis will be available soon",
        "You can discuss this document below",
      ],
      detail:
        "AI summary will be generated after the Python AI service processes this document. Please check back later.",
    };
  });

  const applySummaryResult = (result) => {
    const summary = cleanSummaryText(result.summary || "No summary returned.");
    setAiSummary({
      status: "ready",
      takeaways: summaryTakeaways(summary, result),
      detail: summary,
    });
  };

  const loadExistingSummary = (cancelledRef = { current: false }) => {
    if (!doc?.documentId) return Promise.resolve();

    setAiSummary((prev) => ({ ...prev, status: "loading" }));

    return documentApi
      .getSummary(doc.documentId, publicAccess)
      .then((result) => {
        if (cancelledRef.current) return;
        applySummaryResult(result);
      })
      .catch((err) => {
        if (cancelledRef.current) return;
        if (err.status === 404) {
          const summaryStatus = normalizeSummaryStatus(doc);
          if (isSummaryInProgress(summaryStatus)) {
            setAiSummary((prev) => ({
              ...prev,
              status: "loading",
              detail: "AI summary is being generated in the background.",
            }));
            return;
          }
          if (summaryStatus === "FAILED" || summaryStatus === "UNSUPPORTED") {
            setAiSummary({
              status: "error",
              takeaways: [],
              detail:
                doc?.summaryError ||
                "AI summary could not be generated for this document.",
            });
            return;
          }
          setAiSummary((prev) => ({
            ...prev,
            status: "idle",
            detail:
              "AI summary has not been generated for this document yet.",
          }));
          return;
        }
        setAiSummary({
          status: "error",
          takeaways: [],
          detail: err.message || "Could not load AI summary for this document.",
        });
      });
  };

  const generateSummary = (cancelledRef = { current: false }) => {
    if (!doc?.documentId) return Promise.resolve();

    setAiSummary((prev) => ({ ...prev, status: "loading" }));

    return documentApi
      .summarize(doc.documentId, getDefaultAiUserId())
      .then((result) => {
        if (cancelledRef.current) return;
        if (result.usedMockAi) {
          setAiSummary({
            status: "error",
            takeaways: [],
            detail:
              "AI summary could not be generated right now. Please try again when the AI service is available.",
          });
          return;
        }
        applySummaryResult(result);
      })
      .catch((err) => {
        if (cancelledRef.current) return;
        setAiSummary({
          status: "error",
          takeaways: [],
          detail:
            err.message || "Could not generate AI summary for this document.",
        });
      });
  };

  useEffect(() => {
    if (!doc?.documentId) return;
    if (initialSummaryResult?.summary || initialSummaryError) return;
    const cancelledRef = { current: false };
    loadExistingSummary(cancelledRef);

    return () => {
      cancelledRef.current = true;
    };
  }, [doc?.documentId]);

  useEffect(() => {
    if (!doc?.documentId) return undefined;
    if (!isSummaryInProgress(normalizeSummaryStatus(doc))) return undefined;
    if (aiSummary.status === "ready") return undefined;

    const cancelledRef = { current: false };
    const timer = window.setInterval(async () => {
      try {
        const freshDoc = await documentApi.getById(doc.documentId);
        if (cancelledRef.current) return;
        setDoc(freshDoc);
        await loadExistingSummary(cancelledRef);
      } catch {
        // Keep the current status; the next poll can recover.
      }
    }, 5000);

    return () => {
      cancelledRef.current = true;
      window.clearInterval(timer);
    };
  }, [doc?.documentId, doc?.summaryStatus, aiSummary.status]);

  // Load comments from backend
  const loadComments = async () => {
    if (!doc?.documentId) return;
    try {
      const data = await commentApi.getByDocument(doc.documentId, {
        publicAccess,
        shareId: _shareId,
      });
      setComments(data.map(normalizeComment));
      setTimeout(() => commentsEndRef.current?.scrollIntoView({ behavior: "smooth" }), 100);
    } catch {
      setComments([]);
    }
  };

  useEffect(() => {
    loadComments();
  }, [doc?.documentId]);

  const handleSend = async () => {
    const currentUser = getCurrentUser();
    if (!message.trim() || !doc?.documentId || !currentUser.userId) return;
    setCommentSending(true);
    try {
      await commentApi.create(currentUser.userId, doc.documentId, message.trim());
      setMessage("");
      await loadComments();
    } catch {
      // silently fail
    } finally {
      setCommentSending(false);
    }
  };

  const handleDeleteComment = async (commentId) => {
    const currentUser = getCurrentUser();
    if (!currentUser.userId) return;
    try {
      await commentApi.delete(commentId, currentUser.userId);
      await loadComments();
    } catch {
      // silently fail
    }
  };
  if (docLoading)
    return (
      <div
        className="flex items-center justify-center text-gray-400 text-sm"
        style={{ height: "calc(100vh - 0px)" }}
      >
        Loading document...
      </div>
    );

  if (!doc)
    return (
      <div
        className="flex flex-col bg-white"
        style={{ height: "calc(100vh - 0px)" }}
      >
        {/* Sub-header */}
        <div className="flex items-center justify-between px-6 py-3 border-b border-gray-200 bg-white flex-shrink-0">
          <div className="flex items-center gap-3">
            <button
              onClick={() => navigate(-1)}
              className="text-gray-400 hover:text-gray-700 transition-colors"
            >
              <svg
                width="20"
                height="20"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2.5"
              >
                <polyline points="15 18 9 12 15 6" />
              </svg>
            </button>
            <svg
              width="18"
              height="18"
              viewBox="0 0 24 24"
              fill="none"
              stroke="#4f46e5"
              strokeWidth="2"
            >
              <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
              <polyline points="14 2 14 8 20 8" />
            </svg>
            <span className="text-sm font-bold text-gray-800">
              Document #{documentId}
            </span>
          </div>
        </div>

        {/* Main */}
        <div className="flex flex-1 overflow-hidden">
          <div className="flex-1 bg-gray-100 flex items-center justify-center text-gray-400">
            <div className="text-center">
              <svg
                width="48"
                height="48"
                viewBox="0 0 24 24"
                fill="none"
                stroke="#d1d5db"
                strokeWidth="1.5"
                className="mx-auto mb-3"
              >
                <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
                <polyline points="14 2 14 8 20 8" />
              </svg>
              <p className="text-sm">Document not found</p>
            </div>
          </div>

          <div className="w-[340px] min-w-[340px] border-l border-gray-200 flex flex-col bg-white overflow-hidden">
            <div
              className="overflow-y-auto p-5 border-b border-gray-100"
              style={{ maxHeight: "55%" }}
            >
              <div className="flex items-center justify-between gap-3 mb-4">
              <div className="flex items-center gap-2">
                <svg
                  width="18"
                  height="18"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="#4f46e5"
                  strokeWidth="2"
                >
                  <path d="M12 2L2 7l10 5 10-5-10-5z" />
                  <path d="M2 17l10 5 10-5" />
                  <path d="M2 12l10 5 10-5" />
                </svg>
                <span className="text-[11px] font-black tracking-[2px] text-gray-700 uppercase">
                  AI Summary
                </span>
              </div>
              {!publicAccess && ["idle", "error"].includes(aiSummary.status) && (
                <button
                  type="button"
                  onClick={() => generateSummary()}
                  disabled={aiSummary.status === "loading" || !doc?.documentId}
                  className="h-8 px-3 rounded-lg border border-indigo-200 text-[11px] leading-none font-black text-indigo-600 whitespace-nowrap hover:bg-indigo-50 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  Generate summary
                </button>
              )}
            </div>
              <p className="text-sm font-bold text-indigo-600 mb-2">
                Detailed Summary
              </p>
              <p className="text-sm text-gray-600 leading-relaxed mb-4">
                {aiSummary.detail}
              </p>
            </div>

            <div className="flex flex-col flex-1 overflow-hidden">
              <div className="flex-1 overflow-y-auto p-4 flex flex-col gap-4">
                {comments.map((c) => (
                  <div key={c.id} className="flex gap-2.5 items-start">
                    <div
                      className={
                        "w-8 h-8 rounded-full " +
                        c.avatarBg +
                        " " +
                        c.avatarText +
                        " flex items-center justify-center flex-shrink-0"
                      }
                    >
                      {c.isLogo ? (
                        <svg
                          width="16"
                          height="16"
                          viewBox="0 0 24 24"
                          fill="none"
                        >
                          <circle
                            cx="12"
                            cy="8"
                            r="4"
                            fill="currentColor"
                            opacity="0.6"
                          />
                          <path
                            d="M4 20c0-4 3.6-7 8-7s8 3 8 7"
                            stroke="currentColor"
                            strokeWidth="2"
                            strokeLinecap="round"
                            fill="none"
                          />
                        </svg>
                      ) : (
                        <span className={"text-xs font-bold " + c.avatarText}>
                          {c.initials}
                        </span>
                      )}
                    </div>
                    <div className="flex flex-col gap-0.5 flex-1">
                      <div className="flex items-baseline gap-2">
                        <span className="text-sm font-semibold text-gray-800">
                          {c.name}
                        </span>
                        <span className="text-[11px] text-gray-400">
                          {c.time}
                        </span>
                      </div>
                      <div className="bg-gray-50 rounded-xl rounded-tl-sm px-3 py-2 text-sm text-gray-700 leading-relaxed">
                        {c.text}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
              <div className="px-4 py-3 border-t border-gray-100 flex items-center gap-2">
                <input
                  type="text"
                  value={message}
                  onChange={(e) => setMessage(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && handleSend()}
                  placeholder="Comment"
                  className="flex-1 text-sm px-3 py-2 rounded-xl border border-gray-200 outline-none focus:border-indigo-400 placeholder-gray-400 transition-all"
                />
                <button
                  onClick={handleSend}
                  className="w-9 h-9 bg-indigo-600 hover:bg-indigo-700 rounded-xl flex items-center justify-center text-white transition-colors flex-shrink-0"
                >
                  <svg
                    width="15"
                    height="15"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2.5"
                  >
                    <line x1="22" y1="2" x2="11" y2="13" />
                    <polygon points="22 2 15 22 11 13 2 9 22 2" />
                  </svg>
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    );

  const fileName = doc.documentName || "document";
  const fileExt = fileName.split(".").pop().toUpperCase();
  const canLoadFile = hasPreviewSource(doc);
  return (
    <div
      className="flex flex-col bg-white"
      style={{ height: "calc(100vh - 0px)" }}
    >
      <div className="flex items-center justify-between px-6 py-3 border-b border-gray-200 bg-white flex-shrink-0">
        <div className="flex items-center gap-3">
          <button
            onClick={() => navigate(-1)}
            className="text-gray-400 hover:text-gray-700 transition-colors"
          >
            <svg
              width="20"
              height="20"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2.5"
            >
              <polyline points="15 18 9 12 15 6" />
            </svg>
          </button>
          <svg
            width="18"
            height="18"
            viewBox="0 0 24 24"
            fill="none"
            stroke="#4f46e5"
            strokeWidth="2"
          >
            <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
            <polyline points="14 2 14 8 20 8" />
          </svg>
          <span className="text-sm font-bold text-gray-800">{doc.title}</span>
          <span className="px-2 py-0.5 bg-indigo-600 text-white text-[11px] font-bold rounded-md">
            {fileExt}
          </span>
        </div>
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={handleDownload}
            className="flex items-center gap-2 px-5 py-2 bg-indigo-600 hover:bg-indigo-700 text-white text-sm font-semibold rounded-xl transition-colors"
          >
            <svg
              width="16"
              height="16"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2.5"
            >
              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
              <polyline points="7 10 12 15 17 10" />
              <line x1="12" y1="15" x2="12" y2="3" />
            </svg>
            Download
          </button>
        </div>
      </div>
      <div className="flex flex-1 overflow-hidden">
        <div className="flex-1 overflow-hidden bg-gray-100">
          {previewUrl ? (
            <iframe
              src={previewUrl}
              className="w-full h-full border-0"
              title={doc.title}
            />
          ) : (
            <div className="flex items-center justify-center h-full text-gray-400">
              <div className="text-center">
                <svg
                  width="48"
                  height="48"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="#d1d5db"
                  strokeWidth="1.5"
                  className="mx-auto mb-3"
                >
                  <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
                  <polyline points="14 2 14 8 20 8" />
                </svg>
                <p className="text-sm">{fileError || (canLoadFile ? "Loading preview..." : "No preview available")}</p>
              </div>
            </div>
          )}
        </div>
        <div className="w-[340px] min-w-[340px] border-l border-gray-200 flex flex-col bg-white overflow-hidden">
          <div
            className="overflow-y-auto p-5 border-b border-gray-100"
            style={{ maxHeight: "55%" }}
          >
            <div className="flex items-center justify-between gap-3 mb-4">
              <div className="flex items-center gap-2">
                <svg
                  width="18"
                  height="18"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="#4f46e5"
                  strokeWidth="2"
                >
                  <path d="M12 2L2 7l10 5 10-5-10-5z" />
                  <path d="M2 17l10 5 10-5" />
                  <path d="M2 12l10 5 10-5" />
                </svg>
                <span className="text-[11px] font-black tracking-[2px] text-gray-700 uppercase">
                  AI Summary
                </span>
              </div>
              {!publicAccess && ["idle", "error"].includes(aiSummary.status) && (
                <button
                  type="button"
                  onClick={() => generateSummary()}
                  disabled={aiSummary.status === "loading" || !doc?.documentId}
                  className="h-8 px-3 rounded-lg border border-indigo-200 text-[11px] leading-none font-black text-indigo-600 whitespace-nowrap hover:bg-indigo-50 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  Generate summary
                </button>
              )}
            </div>
            {aiSummary.status === "loading" ? (
              <p className="text-sm text-gray-400 italic">
                Generating summary...
              </p>
            ) : (
              <>
                <p className="text-sm font-bold text-indigo-600 mb-2">
                  Detailed Summary
                </p>
                <p
                  className={
                    "text-sm leading-relaxed mb-4 " +
                    (aiSummary.status === "error"
                      ? "text-red-500"
                      : "text-gray-600")
                  }
                >
                  {aiSummary.detail}
                </p>
              </>
            )}
          </div>
          <div className="flex flex-col flex-1 overflow-hidden">
            <div className="flex-1 overflow-y-auto p-4 flex flex-col gap-4">
              {comments.map((c) => (
                <div key={c.id} className="flex gap-2.5 items-start">
                  <div
                    className={
                      "w-8 h-8 rounded-full " +
                      c.avatarBg +
                      " " +
                      c.avatarText +
                      " flex items-center justify-center flex-shrink-0"
                    }
                  >
                    {c.isLogo ? (
                      <svg
                        width="16"
                        height="16"
                        viewBox="0 0 24 24"
                        fill="none"
                      >
                        <circle
                          cx="12"
                          cy="8"
                          r="4"
                          fill="currentColor"
                          opacity="0.6"
                        />
                        <path
                          d="M4 20c0-4 3.6-7 8-7s8 3 8 7"
                          stroke="currentColor"
                          strokeWidth="2"
                          strokeLinecap="round"
                          fill="none"
                        />
                      </svg>
                    ) : (
                      <span className={"text-xs font-bold " + c.avatarText}>
                        {c.initials}
                      </span>
                    )}
                  </div>
                  <div className="flex flex-col gap-0.5 flex-1">
                    <div className="flex items-baseline gap-2">
                      <span className="text-sm font-semibold text-gray-800">
                        {c.name}
                      </span>
                      <span className="text-[11px] text-gray-400">
                        {c.time}
                      </span>
                    </div>
                    <div className="bg-gray-50 rounded-xl rounded-tl-sm px-3 py-2 text-sm text-gray-700 leading-relaxed">
                      {c.text}
                    </div>
                  </div>
                </div>
              ))}
            </div>
            <div className="px-4 py-3 border-t border-gray-100 flex items-center gap-2">
              <input
                type="text"
                value={message}
                onChange={(e) => setMessage(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && handleSend()}
                placeholder="Comment"
                className="flex-1 text-sm px-3 py-2 rounded-xl border border-gray-200 outline-none focus:border-indigo-400 placeholder-gray-400 transition-all"
              />
              <button
                onClick={handleSend}
                className="w-9 h-9 bg-indigo-600 hover:bg-indigo-700 rounded-xl flex items-center justify-center text-white transition-colors flex-shrink-0"
              >
                <svg
                  width="15"
                  height="15"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2.5"
                >
                  <line x1="22" y1="2" x2="11" y2="13" />
                  <polygon points="22 2 15 22 11 13 2 9 22 2" />
                </svg>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}


